### ISSUE TITLE
download cv2

### ISSUE THREAD

**Issue by silvertakana** [PyExplained/Particle-Simulator#2]
How do I download opencv2?

**Comment by PyExplained** [comment]
Hi silvertakana,
If you're trying to run the simulator on Windows, typing "pip install opencv-python" into the command prompt should work.
If you're using another OS, you could take a look at the official OpenCV documentation (https://pypi.org/project/opencv-python/) for instructions or you could install the ".exe" version of the simulator (https://github.com/PyExplained/Particle-Simulator-.exe-).
Hope this helps :).
