### ISSUE TITLE
License

### ISSUE THREAD

**Issue by weex** [PyExplained/Particle-Simulator#4]
Hi there, this project seems interesting and might be something I'd like to build on. Can I ask if you'd license it as GPL or another copyleft license?

**Comment by PyExplained** [comment]
First of all, thanks a lot for your interest in this project! I'm actually completely new to licensing, so I just took the MIT license (which is quite permissive). For now, I used my online pseudonym, but if that's not sufficient, I can add my real name (I couldn't find a simple answer online about whether or not it's eligible to use a pseudonym, but you can definitely let me know I need to change it).

If you want, you can keep me posted on the things you add to the code. I'm really curious as to what you're going to make with it :).
